nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:5173', 'http://localhost:5174', 'http://localhost:5175']
    allow_headers: ['*']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    expose_headers: ['Link']
    max_age: 3600
    origin_regex: false
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173', 'http://localhost:5174', 'http://localhost:5175']
      allow_headers: ['*']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
      max_age: 3600
