controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

frontend:
    path: /{reactRouting}
    defaults: { reactRouting: null }
    controller: App\\Controller\\HomeController::serveReactApp
    requirements:
        reactRouting: (?!api).*
api:
    resource: '../src/Controller/Api/'
    type: attribute
    prefix: /api
